// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// TaxMuni is an object representing the database table.
type TaxMuni struct {
	ID         int           `boil:"id" json:"id" toml:"id" yaml:"id"`
	MuniID     int           `boil:"muni_id" json:"muni_id" toml:"muni_id" yaml:"muni_id"`
	CategoryID null.Int      `boil:"category_id" json:"category_id,omitempty" toml:"category_id" yaml:"category_id,omitempty"`
	Since      time.Time     `boil:"since" json:"since" toml:"since" yaml:"since"`
	Rate       types.Decimal `boil:"rate" json:"rate" toml:"rate" yaml:"rate"`

	R *taxMuniR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L taxMuniL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TaxMuniColumns = struct {
	ID         string
	MuniID     string
	CategoryID string
	Since      string
	Rate       string
}{
	ID:         "id",
	MuniID:     "muni_id",
	CategoryID: "category_id",
	Since:      "since",
	Rate:       "rate",
}

var TaxMuniTableColumns = struct {
	ID         string
	MuniID     string
	CategoryID string
	Since      string
	Rate       string
}{
	ID:         "tax_muni.id",
	MuniID:     "tax_muni.muni_id",
	CategoryID: "tax_muni.category_id",
	Since:      "tax_muni.since",
	Rate:       "tax_muni.rate",
}

// Generated where

var TaxMuniWhere = struct {
	ID         whereHelperint
	MuniID     whereHelperint
	CategoryID whereHelpernull_Int
	Since      whereHelpertime_Time
	Rate       whereHelpertypes_Decimal
}{
	ID:         whereHelperint{field: "\"alpha\".\"tax_muni\".\"id\""},
	MuniID:     whereHelperint{field: "\"alpha\".\"tax_muni\".\"muni_id\""},
	CategoryID: whereHelpernull_Int{field: "\"alpha\".\"tax_muni\".\"category_id\""},
	Since:      whereHelpertime_Time{field: "\"alpha\".\"tax_muni\".\"since\""},
	Rate:       whereHelpertypes_Decimal{field: "\"alpha\".\"tax_muni\".\"rate\""},
}

// TaxMuniRels is where relationship names are stored.
var TaxMuniRels = struct {
	Category string
	Muni     string
}{
	Category: "Category",
	Muni:     "Muni",
}

// taxMuniR is where relationships are stored.
type taxMuniR struct {
	Category *Category `boil:"Category" json:"Category" toml:"Category" yaml:"Category"`
	Muni     *Muni     `boil:"Muni" json:"Muni" toml:"Muni" yaml:"Muni"`
}

// NewStruct creates a new relationship struct
func (*taxMuniR) NewStruct() *taxMuniR {
	return &taxMuniR{}
}

func (r *taxMuniR) GetCategory() *Category {
	if r == nil {
		return nil
	}
	return r.Category
}

func (r *taxMuniR) GetMuni() *Muni {
	if r == nil {
		return nil
	}
	return r.Muni
}

// taxMuniL is where Load methods for each relationship are stored.
type taxMuniL struct{}

var (
	taxMuniAllColumns            = []string{"id", "muni_id", "category_id", "since", "rate"}
	taxMuniColumnsWithoutDefault = []string{"muni_id", "since", "rate"}
	taxMuniColumnsWithDefault    = []string{"id", "category_id"}
	taxMuniPrimaryKeyColumns     = []string{"id"}
	taxMuniGeneratedColumns      = []string{"id"}
)

type (
	// TaxMuniSlice is an alias for a slice of pointers to TaxMuni.
	// This should almost always be used instead of []TaxMuni.
	TaxMuniSlice []*TaxMuni

	taxMuniQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	taxMuniType                 = reflect.TypeOf(&TaxMuni{})
	taxMuniMapping              = queries.MakeStructMapping(taxMuniType)
	taxMuniPrimaryKeyMapping, _ = queries.BindMapping(taxMuniType, taxMuniMapping, taxMuniPrimaryKeyColumns)
	taxMuniInsertCacheMut       sync.RWMutex
	taxMuniInsertCache          = make(map[string]insertCache)
	taxMuniUpdateCacheMut       sync.RWMutex
	taxMuniUpdateCache          = make(map[string]updateCache)
	taxMuniUpsertCacheMut       sync.RWMutex
	taxMuniUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single taxMuni record from the query using the global executor.
func (q taxMuniQuery) OneG(ctx context.Context) (*TaxMuni, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single taxMuni record from the query.
func (q taxMuniQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TaxMuni, error) {
	o := &TaxMuni{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tax_muni")
	}

	return o, nil
}

// AllG returns all TaxMuni records from the query using the global executor.
func (q taxMuniQuery) AllG(ctx context.Context) (TaxMuniSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all TaxMuni records from the query.
func (q taxMuniQuery) All(ctx context.Context, exec boil.ContextExecutor) (TaxMuniSlice, error) {
	var o []*TaxMuni

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TaxMuni slice")
	}

	return o, nil
}

// CountG returns the count of all TaxMuni records in the query using the global executor
func (q taxMuniQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all TaxMuni records in the query.
func (q taxMuniQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tax_muni rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q taxMuniQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q taxMuniQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tax_muni exists")
	}

	return count > 0, nil
}

// Category pointed to by the foreign key.
func (o *TaxMuni) Category(mods ...qm.QueryMod) categoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CategoryID),
	}

	queryMods = append(queryMods, mods...)

	return Categories(queryMods...)
}

// Muni pointed to by the foreign key.
func (o *TaxMuni) Muni(mods ...qm.QueryMod) muniQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MuniID),
	}

	queryMods = append(queryMods, mods...)

	return Munis(queryMods...)
}

// LoadCategory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (taxMuniL) LoadCategory(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTaxMuni interface{}, mods queries.Applicator) error {
	var slice []*TaxMuni
	var object *TaxMuni

	if singular {
		var ok bool
		object, ok = maybeTaxMuni.(*TaxMuni)
		if !ok {
			object = new(TaxMuni)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTaxMuni)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTaxMuni))
			}
		}
	} else {
		s, ok := maybeTaxMuni.(*[]*TaxMuni)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTaxMuni)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTaxMuni))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &taxMuniR{}
		}
		if !queries.IsNil(object.CategoryID) {
			args = append(args, object.CategoryID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &taxMuniR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.CategoryID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.CategoryID) {
				args = append(args, obj.CategoryID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`alpha.categories`),
		qm.WhereIn(`alpha.categories.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Category")
	}

	var resultSlice []*Category
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Category")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for categories")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for categories")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Category = foreign
		if foreign.R == nil {
			foreign.R = &categoryR{}
		}
		foreign.R.TaxMunis = append(foreign.R.TaxMunis, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CategoryID, foreign.ID) {
				local.R.Category = foreign
				if foreign.R == nil {
					foreign.R = &categoryR{}
				}
				foreign.R.TaxMunis = append(foreign.R.TaxMunis, local)
				break
			}
		}
	}

	return nil
}

// LoadMuni allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (taxMuniL) LoadMuni(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTaxMuni interface{}, mods queries.Applicator) error {
	var slice []*TaxMuni
	var object *TaxMuni

	if singular {
		var ok bool
		object, ok = maybeTaxMuni.(*TaxMuni)
		if !ok {
			object = new(TaxMuni)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTaxMuni)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTaxMuni))
			}
		}
	} else {
		s, ok := maybeTaxMuni.(*[]*TaxMuni)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTaxMuni)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTaxMuni))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &taxMuniR{}
		}
		args = append(args, object.MuniID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &taxMuniR{}
			}

			for _, a := range args {
				if a == obj.MuniID {
					continue Outer
				}
			}

			args = append(args, obj.MuniID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`alpha.muni`),
		qm.WhereIn(`alpha.muni.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Muni")
	}

	var resultSlice []*Muni
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Muni")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for muni")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for muni")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Muni = foreign
		if foreign.R == nil {
			foreign.R = &muniR{}
		}
		foreign.R.TaxMunis = append(foreign.R.TaxMunis, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MuniID == foreign.ID {
				local.R.Muni = foreign
				if foreign.R == nil {
					foreign.R = &muniR{}
				}
				foreign.R.TaxMunis = append(foreign.R.TaxMunis, local)
				break
			}
		}
	}

	return nil
}

// SetCategoryG of the taxMuni to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.TaxMunis.
// Uses the global database handle.
func (o *TaxMuni) SetCategoryG(ctx context.Context, insert bool, related *Category) error {
	return o.SetCategory(ctx, boil.GetContextDB(), insert, related)
}

// SetCategory of the taxMuni to the related item.
// Sets o.R.Category to related.
// Adds o to related.R.TaxMunis.
func (o *TaxMuni) SetCategory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Category) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alpha\".\"tax_muni\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"category_id"}),
		strmangle.WhereClause("\"", "\"", 2, taxMuniPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CategoryID, related.ID)
	if o.R == nil {
		o.R = &taxMuniR{
			Category: related,
		}
	} else {
		o.R.Category = related
	}

	if related.R == nil {
		related.R = &categoryR{
			TaxMunis: TaxMuniSlice{o},
		}
	} else {
		related.R.TaxMunis = append(related.R.TaxMunis, o)
	}

	return nil
}

// RemoveCategoryG relationship.
// Sets o.R.Category to nil.
// Removes o from all passed in related items' relationships struct.
// Uses the global database handle.
func (o *TaxMuni) RemoveCategoryG(ctx context.Context, related *Category) error {
	return o.RemoveCategory(ctx, boil.GetContextDB(), related)
}

// RemoveCategory relationship.
// Sets o.R.Category to nil.
// Removes o from all passed in related items' relationships struct.
func (o *TaxMuni) RemoveCategory(ctx context.Context, exec boil.ContextExecutor, related *Category) error {
	var err error

	queries.SetScanner(&o.CategoryID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("category_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Category = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.TaxMunis {
		if queries.Equal(o.CategoryID, ri.CategoryID) {
			continue
		}

		ln := len(related.R.TaxMunis)
		if ln > 1 && i < ln-1 {
			related.R.TaxMunis[i] = related.R.TaxMunis[ln-1]
		}
		related.R.TaxMunis = related.R.TaxMunis[:ln-1]
		break
	}
	return nil
}

// SetMuniG of the taxMuni to the related item.
// Sets o.R.Muni to related.
// Adds o to related.R.TaxMunis.
// Uses the global database handle.
func (o *TaxMuni) SetMuniG(ctx context.Context, insert bool, related *Muni) error {
	return o.SetMuni(ctx, boil.GetContextDB(), insert, related)
}

// SetMuni of the taxMuni to the related item.
// Sets o.R.Muni to related.
// Adds o to related.R.TaxMunis.
func (o *TaxMuni) SetMuni(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Muni) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alpha\".\"tax_muni\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"muni_id"}),
		strmangle.WhereClause("\"", "\"", 2, taxMuniPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MuniID = related.ID
	if o.R == nil {
		o.R = &taxMuniR{
			Muni: related,
		}
	} else {
		o.R.Muni = related
	}

	if related.R == nil {
		related.R = &muniR{
			TaxMunis: TaxMuniSlice{o},
		}
	} else {
		related.R.TaxMunis = append(related.R.TaxMunis, o)
	}

	return nil
}

// TaxMunis retrieves all the records using an executor.
func TaxMunis(mods ...qm.QueryMod) taxMuniQuery {
	mods = append(mods, qm.From("\"alpha\".\"tax_muni\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"alpha\".\"tax_muni\".*"})
	}

	return taxMuniQuery{q}
}

// FindTaxMuniG retrieves a single record by ID.
func FindTaxMuniG(ctx context.Context, iD int, selectCols ...string) (*TaxMuni, error) {
	return FindTaxMuni(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindTaxMuni retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTaxMuni(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TaxMuni, error) {
	taxMuniObj := &TaxMuni{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"alpha\".\"tax_muni\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, taxMuniObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from tax_muni")
	}

	return taxMuniObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *TaxMuni) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TaxMuni) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no tax_muni provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(taxMuniColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	taxMuniInsertCacheMut.RLock()
	cache, cached := taxMuniInsertCache[key]
	taxMuniInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			taxMuniAllColumns,
			taxMuniColumnsWithDefault,
			taxMuniColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, taxMuniGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(taxMuniType, taxMuniMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(taxMuniType, taxMuniMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"alpha\".\"tax_muni\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"alpha\".\"tax_muni\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into tax_muni")
	}

	if !cached {
		taxMuniInsertCacheMut.Lock()
		taxMuniInsertCache[key] = cache
		taxMuniInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single TaxMuni record using the global executor.
// See Update for more documentation.
func (o *TaxMuni) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the TaxMuni.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TaxMuni) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	taxMuniUpdateCacheMut.RLock()
	cache, cached := taxMuniUpdateCache[key]
	taxMuniUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			taxMuniAllColumns,
			taxMuniPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, taxMuniGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update tax_muni, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"alpha\".\"tax_muni\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, taxMuniPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(taxMuniType, taxMuniMapping, append(wl, taxMuniPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update tax_muni row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for tax_muni")
	}

	if !cached {
		taxMuniUpdateCacheMut.Lock()
		taxMuniUpdateCache[key] = cache
		taxMuniUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q taxMuniQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q taxMuniQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for tax_muni")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for tax_muni")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o TaxMuniSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TaxMuniSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), taxMuniPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"alpha\".\"tax_muni\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, taxMuniPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in taxMuni slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all taxMuni")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *TaxMuni) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TaxMuni) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no tax_muni provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(taxMuniColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	taxMuniUpsertCacheMut.RLock()
	cache, cached := taxMuniUpsertCache[key]
	taxMuniUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			taxMuniAllColumns,
			taxMuniColumnsWithDefault,
			taxMuniColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			taxMuniAllColumns,
			taxMuniPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, taxMuniGeneratedColumns)
		update = strmangle.SetComplement(update, taxMuniGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert tax_muni, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(taxMuniPrimaryKeyColumns))
			copy(conflict, taxMuniPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"alpha\".\"tax_muni\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(taxMuniType, taxMuniMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(taxMuniType, taxMuniMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert tax_muni")
	}

	if !cached {
		taxMuniUpsertCacheMut.Lock()
		taxMuniUpsertCache[key] = cache
		taxMuniUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single TaxMuni record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *TaxMuni) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single TaxMuni record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TaxMuni) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TaxMuni provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), taxMuniPrimaryKeyMapping)
	sql := "DELETE FROM \"alpha\".\"tax_muni\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from tax_muni")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for tax_muni")
	}

	return rowsAff, nil
}

func (q taxMuniQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q taxMuniQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no taxMuniQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tax_muni")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tax_muni")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o TaxMuniSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TaxMuniSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), taxMuniPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"alpha\".\"tax_muni\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, taxMuniPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from taxMuni slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tax_muni")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *TaxMuni) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no TaxMuni provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TaxMuni) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTaxMuni(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TaxMuniSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty TaxMuniSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TaxMuniSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TaxMuniSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), taxMuniPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"alpha\".\"tax_muni\".* FROM \"alpha\".\"tax_muni\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, taxMuniPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TaxMuniSlice")
	}

	*o = slice

	return nil
}

// TaxMuniExistsG checks if the TaxMuni row exists.
func TaxMuniExistsG(ctx context.Context, iD int) (bool, error) {
	return TaxMuniExists(ctx, boil.GetContextDB(), iD)
}

// TaxMuniExists checks if the TaxMuni row exists.
func TaxMuniExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"alpha\".\"tax_muni\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if tax_muni exists")
	}

	return exists, nil
}
